<?php echo $this->doctype(); ?>

<html lang="ru">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Отправка сообщений')->setSeparator(' | '); ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

        ->prependStylesheet($this->basePath('css/chat_style.css'))
        ;
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))


        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.11/jquery.mousewheel.min.js')
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/jquery.jscrollpane.min.js')
        ->prependFile($this->basePath('js/index.js'))
        ;
    ?>
    <?php
//    $this->holidays();
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    ?>
    <script type="text/javascript">
//        (function () {
//            if ((("Microsoft Internet Explorer" == navigator.appName) || // IE < 11
//                navigator.userAgent.match(/Trident\/./i))) { // IE 11
//                var script_es5 = document.createElement('script');
//                var script_es6 = document.createElement('script');
//                script_es5.type = script_es6.type = 'text/javascript';
//                script_es5.src = '<?//=$this->basePath() . '/assets/js/es5-shim.min.js'?>//';
//                script_es6.src = '<?//=$this->basePath() . '/assets/js/es6-shim.min.js'?>//';
//                document.getElementsByTagName('head')[0].appendChild(script_es5);
//                document.getElementsByTagName('head')[0].appendChild(script_es6);
//            }
//        })();
    </script>
    <?= $this->plugin('HeadScript'); ?>
    <link href="//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic" rel="stylesheet"
          type="text/css">
</head>

<body>
<div id="demo_navi">
    <a href="http://www.rudebox.org.ua/ " rel="nofollow">
        <div class="logo"><b><font color=#c3e425>RUDE</font>BOX</b></div>
    </a>
    <div class="demo">DEMO</div>
    <a href="http://www.rudebox.org.ua/create-design-for-chat-site-to-using-css" class="go-bottom" rel="nofollow">
        <div class="name">Создаем дизайн чата для сайта с помощью CSS3</div>
    </a>
</div>
<br><br><br><br><br><br>
<div class="window-wrapper">
    <div class="window-title">
        <div class="dots">
            <i class="fa fa-circle"></i>
            <i class="fa fa-circle"></i>
            <i class="fa fa-circle"></i>
        </div>
        <div class="title">
            <span>Чат</span>
        </div>
        <div class="expand">
            <i class="fa fa-expand"></i>
        </div>
    </div>
    <div class="window-area">
        <div class="conversation-list">
            <ul class="">
                <li class="item"><a href="#"><i class="fa fa-list-alt"></i><span>Учасники</span></a></li>
                <li class="item active"><a href="#"><i class="fa fa-user"></i><span>Команда чата</span><i
                            class="fa fa-times"></i></a></li>
                <li><a href="#"><i class="fa fa-circle-o online"></i></i><span>Кристина Галеева</span><i
                            class="fa fa-times"></i></a></li>
                <li><a href="#"><i class="fa fa-circle-o idle"></i></i><span>Давид Барто</span><i
                            class="fa fa-times"></i></a></li>
                <li><a href="#"><i class="fa fa-circle-o offline"></i></i><span>Сергей Бондарь</span><i
                            class="fa fa-times"></i></a></li>
                <li><a href="#"><i class="fa fa-circle-o offline"></i></i><span>Глеб Кавраский</span><i
                            class="fa fa-times"></i></a></li>
            </ul>
            <div class="my-account">
                <div class="image">
                    <img src="de76e03aa6b5b0bf675c1e8a990da52f.jpg">
                    <i class="fa fa-circle online"></i>
                </div>
                <div class="name">
                    <span>Кристина Галеева</span>
                    <i class="fa fa-angle-down"></i>
                    <span class="availability">В сети</span>
                </div>

            </div>
        </div>
        <div class="chat-area">
            <div class="title"><b>Переписка</b><i class="fa fa-search"></i></div>
            <div class="chat-list">
                <ul>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>Hey, do you like the new interface? It's done with Font Awesome.</p>
                            <span class="msg-time">5:00 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">David Barto</span>
                        </div>
                        <div class="message">
                            <p><span class="blue-label">Kristi Galeeva</span> I see what you did there.</p>
                            <span class="msg-time">5:01 pm</span>
                        </div>
                    </li>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>Feel free to look at the code if you want.</p>
                            <span class="msg-time">5:02 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">Gleb Kavrasky</span>
                        </div>
                        <div class="message">
                            <p>Yeah, will do.</p>
                            <span class="msg-time">5:04 pm</span>
                        </div>
                    </li>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>This is an example text reply.</p>
                            <span class="msg-time">5:04 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">Christian Smith</span>
                        </div>
                        <div class="message">
                            <p>I know, put some more.</p>
                            <span class="msg-time">5:06 pm</span>
                        </div>
                    </li>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>Here is another line.</p>
                            <span class="msg-time">5:06 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">Gleb Kavrasky</span>
                        </div>
                        <div class="message">
                            <p>Yeah, will do.</p>
                            <span class="msg-time">5:04 pm</span>
                        </div>
                    </li>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>Feel free to look at the code if you want.</p>
                            <span class="msg-time">5:02 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">David Barto</span>
                        </div>
                        <div class="message">
                            <p>Yeah, will do.</p>
                            <span class="msg-time">5:04 pm</span>
                        </div>
                    </li>
                    <li class="me">
                        <div class="name">
                            <span class="">Kristi Galeeva</span>
                        </div>
                        <div class="message">
                            <p>Feel free to look at the code if you want.</p>
                            <span class="msg-time">5:02 pm</span>
                        </div>
                    </li>
                    <li class="">
                        <div class="name">
                            <span class="">Sergey Bondar</span>
                        </div>
                        <div class="message">
                            <p>Yeah, will do.</p>
                            <span class="msg-time">5:04 pm</span>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="input-area">
                <div class="input-wrapper">
                    <input type="text" value="">
                    <i class="fa fa-smile-o"></i>
                    <i class="fa fa-paperclip"></i>
                </div>
                <input type="button" value="Ввод" class="send-btn">
            </div>
        </div>
        <div class="right-tabs">
            <ul class="tabs">
                <li class="active">
                    <a href="#"><i class="fa fa-users"></i></a>
                </li>
                <li><a href="#"><i class="fa fa-paperclip"></i></a></li>
                <li><a href="#"><i class="fa fa-link"></i></a></li>
            </ul>
            <ul class="tabs-container">
                <li class="active">
                    <ul class="member-list">
                        <li><span class="status online"><i class="fa fa-circle-o"></i></span><span>Kristi Galeeva</span>
                        </li>
                        <li><span class="status online"><i class="fa fa-circle-o"></i></span><span>Segey Bondar</span>
                        </li>
                        <li><span class="status idle"><i
                                    class="fa fa-circle-o"></i></span><span>Gleb Kavrasky</span><span class="time">10:45 pm</span>
                        </li>
                        <li><span class="status offline"><i class="fa fa-circle-o"></i></span><span>David Barto</span>
                        </li>
                    </ul>
                </li>
                <li></li>
                <li></li>
            </ul>
            <i class="fa fa-cog"></i>
        </div>
    </div>
</div>



</body>

</html>
