<?php echo $this->doctype(); ?>

<html lang="ru_RU">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>

    <?= $this->headTitle('Отправка сообщений')->setSeparator(' | '); ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php
//    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
////        ->prependStylesheet($this->basePath('css/style.css'))
//        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
//    ;
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

    <?php
    echo $this->plugin('HeadScript');
    echo $this->plugin('HeadLink');
    ?>


</head>
<body>
<section>
    <main>
        <?= $this->content; ?>
    </main>
</section>

<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js'></script>
    <?php echo $this->inlineScript(); ?>
</body>
</html>
